package com.cmt.services.helper

object IServiceConstants {
    object API {
        const val login = "login"
        const val register = "register"
        const val verify_otp = "otp_verify"
        const val resend_otp = "resend_otp"
        const val change_password = "change_password"
        const val forgot_password = "forgot_password"
        const val version_check = "version_check"

        const val profile = "profile"
        const val test_result = "mock_test_questions/rank"
        const val razerpayorderid = "razerpayorderid"
        const val payment_success = "payment_success"
        const val update_profile = "update_profile"
        const val about_us = "about_us"
        const val faq = "faq"
        const val support = "support"
        const val contact_us = "contact_us"
        const val terms = "terms_conditions"
        const val courses = "courses"
        const val banners = "banners"
        const val ebooks = "ebooks"
        const val Course_categories = "Course_categories"
        const val package_details = "package_details"
        const val my_courses = "my_courses"
        const val view_result = "view_result"
        const val search = "search"
        const val Course_subjects = "Course_subjects"
        const val my_materials = "my_materials"
        const val Subject_materials = "Subject_materials"
        const val my_orders = "my_orders"
        const val mock_test_questions = "mock_test_questions"
        const val submit_ex = "mock_test_questions/submit_exam"
        const val start_exam = "start_exam"
        const val submit_exam = "submit_exam"
        const val review_exam = "review_exam"
        const val packages = "packages"
        const val privacy = "privacy_policy"
        const val homepage = "homepage"
        const val enquiries = "enquiries"
        const val feedback = "feedback/submit_feedback"
        const val categories = "categories"
        const val materials = "materials"
        const val search_materials = "search_materials"
        const val logout = "logout"
        const val reset_password = "reset_password"
        const val notifications = "notifications"
        const val auto_login = "auto_login"
        const val getPackages = "courses/getPackages"
        const val paymentDetails = "courses/getPaymentDetails"


    }

}